[package]
name = "ether_test"
version = "0.1.0"
authors = ["Michal Podhradsky <mpodhradsky@galois.com>"]

[dependencies]
tun-tap = "0.1.1"
ivyrust = {git="https://github.com/paparazzi/ivy-rust"}
clap = {version = "~2.27.0", features = ["yaml"]}
lazy_static = "1.2.0"